version: 0.2

phases:
  install:
    commands:
      # - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      # - sudo apt-get install -y nodejs
      # - sudo apt update
      # - sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
      # - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      # - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      # - sudo apt update
      # - sudo apt install -y docker-ce
      # - sudo apt install -y docker-compose
      - echo $USER
      - docker -v
      - docker-compose -v
      # - sudo apt-get update && sudo apt-get -y dist-upgrade
      # - sudo apt-get install -y mysql-client

  pre_build:
    commands:
      - chmod +x ./tools/db/start.sh
      - ./tools/db/start.sh
      - docker ps
      - sleep 1m
      - chmod +x ./tools/db/update-mysql-grant.sh
      - ./tools/db/update-mysql-grant.sh
      - chmod +x ./tools/install_all_node_modules.sh
      - ./tools/install_all_node_modules.sh

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/services/api
      - npm run deploy:dev
      - cd $CODEBUILD_SRC_DIR/services/back
      - npm run deploy:dev
