version: 0.2

phases:
  install:
    commands:
      - echo $USER
      - docker -v
      - docker-compose -v
      # - sudo apt-get update && sudo apt-get -y dist-upgrade
      # - sudo apt-get install -y mysql-client

  pre_build:
    commands:
      - chmod +x ./tools/db/start.sh
      - ./tools/db/start.sh
      - docker ps
      - sleep 10
      - chmod +x ./tools/db/update-mysql-grant.sh
      - ./tools/db/update-mysql-grant.sh
      - chmod +x ./tools/install_all_node_modules.sh
      - ./tools/install_all_node_modules.sh

  build:
    commands:
      - chmod +x ./tools/services/test-all-services.sh
      - ./tools/services/test-all-services.sh

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/services/api
      - npm run deploy:dev
      - cd $CODEBUILD_SRC_DIR/services/back
      - npm run deploy:dev
