version: 0.2

phases:
  install:
    commands:
      - chmod +x ./tools/install_all_node_modules.sh
      - ./tools/install_all_node_modules.sh
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/services/api
      - npm run deploy:prod
      - cd $CODEBUILD_SRC_DIR/services/back
      - npm run deploy:prod