-- USE product;

-- DELETE FROM product_size_details;

-- DELETE FROM product_variations;

-- DELETE FROM suppliers;

-- DELETE FROM products;

-- INSERT INTO suppliers(
--     id
--   , name_ko
--   , name_en
--   , address
--   , tel
--   , date_created
--   , date_updated
-- ) VALUES (
--     1
--   , '공급사1'
--   , 'supplier1'
--   , '서울 강남구 영동대로 123'
--   , '02-1234-1234'
--   , NOW()
--   , NOW()
-- ), (
--     2
--   , '공급사2'
--   , 'supplier2'
--   , '서울 종로구 종로 123'
--   , '02-5678-5678'
--   , NOW()
--   , NOW()
-- ), (
--     3
--   , '공급사3'
--   , 'supplier3'
--   , '서울 마포구 월드컵로 1'
--   , '02-1544-5555'
--   , NOW()
--   , NOW()
-- );

-- INSERT INTO products (
--     id
--   , category
--   , hidden
--   , draft_step
--   , status
--   , name_ko
--   , name_en
--   , name_ja
--   , supplier_id
--   , supply_price
--   , price
--   , attribute1_name
--   , attribute1_option_list
--   , attribute2_name
--   , attribute2_option_list
--   , supply_name
--   , date_ymd_manufactured
--   , date_ymd_published
--   , origin_country_code
--   , weight
--   , composition_en
--   , composition_ja
--   , additional_information
--   , date_created
--   , date_updated
-- ) VALUES (
-- -- draft product
--     1
--   , null
--   , null
--   , 0
--   , 0
--   , null
--   , null
--   , null
--   , 1
--   , 10000
--   , null
--   , 'color'
--   , 'black,white'
--   , 'size'
--   , '44,55,66'
--   , '오버핏자켓'
--   , 20190104
--   , null
--   , null
--   , null
--   , 'polyester100%'
--   , null
--   , null
--   , NOW()
--   , NOW()
-- ), (
-- -- draft product
--     2
--   , null
--   , null
--   , 0
--   , 0
--   , null
--   , null
--   , null
--   , 1
--   , 20000
--   , null
--   , 'color'
--   , 'blue'
--   , 'size'
--   , 'free'
--   , '벨트 야상 점퍼'
--   , 20190104
--   , null
--   , null
--   , null
--   , 'polyester80%,cotton20%'
--   , null
--   , null
--   , NOW()
--   , NOW()
-- ), (
-- -- draft product
--     3
--   , null
--   , null
--   , 0
--   , 0
--   , null
--   , null
--   , null
--   , 2
--   , 25000
--   , null
--   , 'color'
--   , 'navy'
--   , 'size'
--   , 'M,L'
--   , '데일리 가디간'
--   , 20190104
--   , null
--   , null
--   , null
--   , 'cotton100%'
--   , null
--   , null
--   , NOW()
--   , NOW()
-- ), (
-- -- detail product
--     4
--   , 'cardigan'
--   , 0
--   , 1
--   , 0
--   , '소프트 골지 가디건'
--   , 'soft cardigan'
--   , null
--   , 3
--   , 25000
--   , 40000
--   , 'color'
--   , 'black,grey'
--   , 'size'
--   , 'S,M,L'
--   , '소프트 골지 가디건'
--   , 20190104
--   , 20190105
--   , 'KR'
--   , 200
--   , 'cotton100%'
--   , null
--   , '{}'
--   , NOW()
--   , NOW()
-- ), (
-- -- detail product
--     5
--   , 'cardigan'
--   , 0
--   , 1
--   , 0
--   , '라인 가디건'
--   , 'line cardigan'
--   , null
--   , 3
--   , 30000
--   , 45000
--   , 'color'
--   , 'yellow,orange'
--   , 'size'
--   , 'free'
--   , '라인 가디건'
--   , 20190104
--   , 20190105
--   , 'KR'
--   , 250
--   , 'cotton100%'
--   , null
--   , '{}'
--   , NOW()
--   , NOW()
-- ), (
-- -- translated product
--     6
--   , 't_shirt'
--   , 0
--   , 7
--   , 0
--   , '캐주얼 라운드 티셔츠'
--   , 'casual rount t shirt'
--   , 'カジュアルクルーネックTシャツ'
--   , 1
--   , 50000
--   , 60000
--   , 'color'
--   , 'mix'
--   , 'size'
--   , 'M,L'
--   , '캐주얼 라운드 티셔츠'
--   , 20190204
--   , 20190205
--   , 'KR'
--   , 300
--   , 'cotton100%'
--   , 'コットン100%'
--   , '{}'
--   , NOW()
--   , NOW()
-- ), (
-- -- translated product
--     7
--   , 't_shirt'
--   , 0
--   , 7
--   , 0
--   , '라인 포인트 티셔츠'
--   , 'line point t shirt'
--   , 'ラインポイントTシャツ'
--   , 1
--   , 40000
--   , 40000
--   , 'color'
--   , 'white,brown'
--   , 'size'
--   , 'S,M,L'
--   , '라인 포인트 티셔츠'
--   , 20190110
--   , 20190111
--   , 'KR'
--   , 350
--   , 'polyester80%,cotton20%'
--   , 'ポリエステル80%,コットン20%'
--   , '{}'
--   , NOW()
--   , NOW()
-- ), (
-- -- published product
--     8
--   , 'etc_skirt'
--   , 0
--   , 7
--   , 1
--   , '호피 미니스커트'
--   , 'tiger pattern mini skirt'
--   , 'ヒョウミニスカート'
--   , 2
--   , 25000
--   , 30000
--   , 'color'
--   , 'mixed'
--   , 'size'
--   , '24,25,26'
--   , '호피 미니스커트'
--   , 20190110
--   , 20190111
--   , 'KR'
--   , 350
--   , 'polyester80%,cotton20%'
--   , 'ポリエステル80%,コットン20%'
--   , '{}'
--   , NOW()
--   , NOW()
-- ), (
-- -- published product
--     9
--   , 'etc_skirt'
--   , 0
--   , 7
--   , 1
--   , '페미닌 니트 스커트'
--   , 'feminine knitted skirt'
--   , 'フェミニンニットスカート'
--   , 2
--   , 28000
--   , 39000
--   , 'color'
--   , 'pink,yellow'
--   , 'size'
--   , 'S,M,L'
--   , '페미닌 니트 스커트'
--   , 20190115
--   , 20190115
--   , 'KR'
--   , 350
--   , 'polyester80%,cotton20%'
--   , 'ポリエステル80%,コットン20%'
--   , '{}'
--   , NOW()
--   , NOW()
-- ), (
-- -- published product
--     10
--   , 'etc_skirt'
--   , 0
--   , 7
--   , 2
--   , '버튼 스커트'
--   , 'button skirt '
--   , 'サイドボタンロングスカート'
--   , 1
--   , 35000
--   , 40000
--   , 'color'
--   , 'pink,yellow'
--   , 'size'
--   , 'S,M,L'
--   , '버튼 스커트'
--   , 20190115
--   , 20190115
--   , 'KR'
--   , 350
--   , 'polyester80%,cotton20%'
--   , 'ポリエステル80%,コットン20%'
--   , '{}'
--   , NOW()
--   , NOW()
-- );
